# Generated by Django 4.1.2 on 2023-01-26 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_foodconsumed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytoburnout',
            name='duration',
            field=models.TimeField(max_length=100),
        ),
    ]
