# Generated by Django 4.1.2 on 2023-01-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_alter_activitytoburnout_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytoburnout',
            name='duration',
            field=models.CharField(max_length=100),
        ),
    ]
