# Generated by Django 4.1.2 on 2023-01-26 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodapp', '0004_alter_activitytoburnout_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytoburnout',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitytoburnout',
            name='is_global',
            field=models.BooleanField(default=True),
        ),
    ]
