# Generated by Django 4.1.2 on 2023-01-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0005_activitytoburnout_added_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytoburnout',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
