# Generated by Django 4.1.2 on 2023-01-26 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0007_foodconsumed_user_activityrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityrecord',
            old_name='activity_id',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='activityrecord',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='foodconsumed',
            old_name='food_id',
            new_name='food',
        ),
    ]
