# Generated by Django 4.1.2 on 2023-01-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0008_rename_activity_id_activityrecord_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityrecord',
            name='calorie_burned',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
